### ISSUE TITLE
not working :-(

### ISSUE THREAD

**Issue by guteSeite** [hackffm/ESP32_BadApple#1]
code is running, upload was ok.
after mounting message i get a black screen.

**Comment by Tuet** [comment]
Hi, try to download MKSPIFFS in your appropriate version from here https://github.com/igrr/mkspiffs/releases/tag/0.2.2 and replace the executable in your <sketchbook>\hardware\espressif\esp32\tools\mkspiffs with that. Try to re-upload the video data and report. This is the bug I mentioned in the current release of Arduino ESP32 (will be fixed soon after chinese new-year I think...)

**Comment by guteSeite** [comment]
the video upload is not the problem. i have the data on serial but not on display(Heltec esp32 with oled ssd1306) :-(

**Comment by Tuet** [comment]
Yes, both mkspiffs versions are able to UPLOAD the SPIFFS data to the ESP32 - but only the latest version does it storing in a format, that the Arduino ESP32 SPIFFS in it's current version is able to read without reading only garbage...

**Comment by guteSeite** [comment]
OK, now it's working - cool!!!
for me it was not "mkspiffs-0.2.2-arduino-esp32-win32.zip"
but "mkspiffs-0.2.2-generic-win32.zip" !!!
thanks

**Comment by Tuet** [comment]
With the current version of Arduino ESP32 the SPIFFS issue is closed, so no more patching needed. In case it does not work, please reinstall your Arduino ESP32 plugin to upgrade it.
